# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX2185/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX2185

PRODUCT_COPY_FILES += \
    vendor/realme/RMX2185/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/realme/RMX2185/proprietary/product/etc/apns-conf.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/apns-conf.xml \
    vendor/realme/RMX2185/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/realme/RMX2185/proprietary/lib/libem_support_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libem_support_jni.so \
    vendor/realme/RMX2185/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/realme/RMX2185/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/RMX2185/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/realme/RMX2185/proprietary/lib64/libem_support_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libem_support_jni.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/etc/diracmobile.config:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/etc/diracmobile.config \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/lib/libDiracAPI_SHARED.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/libDiracAPI_SHARED.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/lib/libdpframework.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/libdpframework.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/lib/soundfx/libdirac.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/soundfx/libdirac.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/lib64/libdpframework.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib64/libdpframework.so \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Cupid_Pink:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Cupid_Pink \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Cupid_Pink.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Cupid_Pink.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Lavender:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Lavender \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Lavender.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Lavender.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Mauve_Purple:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Mauve_Purple \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Mauve_Purple.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Mauve_Purple.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Medium_Aquamarine:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Medium_Aquamarine \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Medium_Aquamarine.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Medium_Aquamarine.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Medium_Turquoise:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Medium_Turquoise \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Medium_Turquoise.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Medium_Turquoise.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Pale_Cornflower_Blue:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Pale_Cornflower_Blue \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Pale_Cornflower_Blue.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Pale_Cornflower_Blue.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Rajah_Orange:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Rajah_Orange \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Rajah_Orange.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Rajah_Orange.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Sky_Blue:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Sky_Blue \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Sky_Blue.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Sky_Blue.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Sundown:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Sundown \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Sundown.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Sundown.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Vivid_Yellow:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Vivid_Yellow \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Vivid_Yellow.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Vivid_Yellow.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Wild_Willow:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Wild_Willow \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Light_Wild_Willow.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Light_Wild_Willow.zip \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Oigiri_Board:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Oigiri_Board \
    vendor/realme/RMX2185/proprietary/etc/gboard_theme/Oigiri_Board.zip:$(TARGET_COPY_OUT_SYSTEM)/etc/gboard_theme/Oigiri_Board.zip \
    vendor/realme/RMX2185/proprietary/etc/default-permissions/default-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/default-permissions.xml \
    vendor/realme/RMX2185/proprietary/etc/permissions/privapp-permissions-op-launcher.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-op-launcher.xml \
    vendor/realme/RMX2185/proprietary/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/29/bin/hw/vendor.oppo.hardware.biometrics.fingerprint@2.1-service:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/bin/hw/vendor.oppo.hardware.biometrics.fingerprint@2.1-service

PRODUCT_PACKAGES += \
    EngineerMode \
    ImsService
